spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.144.168.206:3306/sell?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

server:
  port: 8081

girl:
  name: lili
  age: 29
